AllCops:
  TargetRubyVersion: 3.3 # Applicable rules for Ruby versions 3.2 and above.
  NewCops: enable          # Enables new rules. Ensures new rules added in later versions are checked.

Layout/LineLength:
  Max: 150                  # Enforces a maximum line length of 150 characters.
  Exclude:
    - 'lib/role_functions.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes # Enforces the use of double quotes for strings.

Style/FrozenStringLiteralComment:
  Enabled: true                  # Requires the `# frozen_string_literal: true` comment at the top of the file.

Layout/IndentationWidth:
  Width: 2                  # Sets the indentation width to 2 spaces.

Metrics/MethodLength:
  Max: 100                  # Enforces a maximum length of 100 lines for a method.

Metrics/ClassLength:
  Max: 500                  # Enforces a maximum length of 500 lines for a class.

Style/Documentation:
  Enabled: false

Rails/I18nLazyLookup:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

require:
  - rubocop-rails                  # Enable rubocop-rails extension
