AllCops:
  TargetRubyVersion: ~> 3.2 # Applicable rules for Ruby versions 3.2 and above.
  NewCops: enable          # Enables new rules. Ensures new rules added in later versions are checked.

Metrics/LineLength:
  Max: 80                  # Enforces a maximum line length of 80 characters.
                           # Example: If `puts 'This is a line'` exceeds 80 characters, it will raise a warning.

Style/StringLiterals:
  EnforcedStyle: double_quotes # Enforces the use of double quotes for strings.
                           # Example: A warning will be raised if `'This is a string'` is used instead of `"This is a string"`.

Style/FrozenStringLiteralComment:
  Enabled: true            # Requires the `# frozen_string_literal: true` comment at the top of the file.
                           # This makes strings immutable. Example:
                           # Use `s = 'test'.freeze` instead of `s = 'test'`.

Layout/IndentationWidth:
  Width: 2                 # Sets the indentation width to 2 spaces.
                           # Example:
                           # ```
                           # def method
                           #   if condition
                           #     do_something
                           #   end
                           # end
                           # ```

Naming/VariableName:
  AllowedNames: ['_*']     # Allows variable names that start with `_` (e.g., `_variable`).
                           # Example: `_temp_var` is valid, while `1var` is invalid.

Metrics/MethodLength:
  Max: 70                  # Enforces a maximum length of 70 lines for a method.
                           # Example: A warning will be raised if a method exceeds 70 lines.

Metrics/ClassLength:
  Max: 500                 # Enforces a maximum length of 500 lines for a class.
                           # Example: A warning will be raised if a class exceeds 500 lines.

Rails/HttpStatus:
  EnforcedStyle: symbol     # Enforces the use of symbols for HTTP status codes.
                           # Example: `:ok` is preferred over `200`.
